config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/about'
  get 'home/search'
  get 'home/search_stocks'

  post '/home/search' => 'home/search'
  post '/home/search_stocks' => 'home/search_stocks'
  
  #get '/cryptos/new', to: 'cryptos#new' as: 'new_crypto'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=3faaac7a-4b4d-44d3-9001-1cb1e966e9ce'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @my_coins = ["BTC", "ETH", "SHIB", "MANA", "CRO"]

    #@my_coins = @coins.values[1]
    
    #@my_coins = ["symbol"][0-141]
    # ['symbol'][0-141]
    #["BTC", "ETH", "SHIB", "MANA", "CRO"]
    # ['cmc_rank'][1-100]
  end

  def about
  end

  def search
    require 'net/http'
    require 'json'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=3faaac7a-4b4d-44d3-9001-1cb1e966e9ce'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @search_coin = JSON.parse(@response)
    
    @symbol = params[:sym] 
    if @symbol
      @symbol = @symbol.upcase
    end

    if @symbol == ""
      @symbol = "Please enter a cryptocurrency to search."
    end

  end
  
  def search_stocks
  end
end


#<li><%= link_to "List Cryptos", cryptos_path %></li>
#<li><%= link_to "Add New", new_crypto_path %></li>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %> 
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Crypto Portfolio", root_path, class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">

      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About Us", home_about_path %></li>

      <% if user_signed_in? %>

        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
  
    </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Us</h2>
<p>My name is Vincent Tran</p>

app/views/home/flash.html.erb
<% flash.each do |name, msg| %> 
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/index.html.erb
<h1>Finance Portfolio Manager</h1>
<p>This is my first rails app!</p>
<br><br>

<% @coins %>

<% for x in @coins['data'] %>

 <% for coin in @my_coins  %>
     <% if coin == x['symbol'] %>
         <%= x['name'] %>: $<%= x['quote']['USD']['price'] %> <br>
         Rank: <%= x['cmc_rank'] %> <br><br>
     <% end %>
    
 <% end %>


<% end %>

<%= link_to "Search crypto or stocks", home_search_path %>

app/views/home/search.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Search for a specific cryptocurrency or stock.</h3>
  </div>
<div class="panel-body">

<br>

<%= form_tag home_search_path, :method => 'POST' do %>
    <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 %>
    <%= submit_tag 'Lookup Quote' %>
<% end %>

<br><br>

<%= form_tag home_search_path, :method => 'POST' do %>
    <%= text_field_tag 'sym', nil, placeholder: 'Enter Stock Symbol', size: 50 %>
    <%= submit_tag 'Lookup Quote' %>
<% end %>

<br>

<br><br>

<% if @symbol %>
    <% for x in @search_coin['data'] %>
        <% if @symbol == x['symbol'] %>
            <%= x['symbol'] %> <br><br>
            <%= x['name'] %>: <br><br> 
           $ <%= x['quote']['USD']['price'] %> <br><br>
            Rank: <%= x['cmc_rank'] %> <br><br>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finances Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  
<%= render 'home/navbar' %>

<div class="container">

<%= render 'home/flash' %>
    <%= yield %>
</div>

  </body>
</html>